src.dir=src
tool.dir=tools
build.dir=build
class.dir=${build.dir}/classes
doc.dir=doc
dist.dir=dist
results.dir=results
test.dir=test
tool.jars=${tool.dir}/jars
junit.jar=${tool.jars}/junit-platform-console-standalone-6.1.0-M1.jar
junit.results.dir=${results.dir}/junit
pmd.dir=${tool.dir}/pmd
pmd.home=${tool.dir}/pmd
checkstyle.dir=${tool.dir}/checkstyle
checkstyle.jar=${tool.jars}/checkstyle-13.3.0-all.jar
checkstyle.suppressions.file=suppressions.xml
checkstyle.importcontrol.file=import-control.xml
translation.severity=warning
spotbugs.home=tools/spotbugs
jacoco.dir=${tool.dir}/jacoco
jacoco.jar=${tool.jars}/jacocoant.jar
jacoco.results.dir=${results.dir}/jacoco
jacoco.exec.file=${results.dir}/jacoco/jacoco.exec
project.name=StickNotes
main.class=StickyNoteMain
test.driver=${main.class}Test
